### ISSUE TITLE
You probably shouldn't put your passwords on the internet...

### ISSUE THREAD

**Issue by connorslade** [akhilvanka/akhilvanka.github.io#1]
First off, your site looks really nice.
But more importantly, you should be careful about what you put on the internet...

Line `18` of your [index.html](https://github.com/akhilvanka/akhilvanka.github.io/blob/58f45997130d5d0dee8ce4105e1358e7e3104a18/index.html#L18) says `            <li><a href="https://students.genesisedu.com/bernardsboe/parents?tab1=studentdata&tab2=studentsummary&studentid=306063&action=form"/>genesis</li>`. The problem is that in the query string you have your student ID (aka your password). This means the other people could sign in to your school google / genesis account.

To fix this, try making the link just `https://students.genesisedu.com/bernardsboe`.

**Comment by akhilvanka** [comment]
Ah thanks for letting me know, It must have slipped through when I was checking everything.
